"""
Script to generate cleanly quoted courses.csv with 120+ rich courses.
"""

import csv
import os

courses = [
    # AI & Machine Learning
    {"course_id": "C001", "title": "Machine Learning Specialization", "provider": "Coursera (Stanford/DeepLearning.AI)", "category": "AI & Machine Learning", "level": "Beginner", "rating": 4.9, "duration_hours": 60, "price_usd": 49.00, "skills_covered": "Python; Linear Algebra; Supervised Learning; Unsupervised Learning; Neural Networks", "prerequisites": "Basic Python", "description": "Foundational machine learning program taught by Andrew Ng covering algorithms and practical applications.", "url": "https://www.coursera.org/specializations/machine-learning-introduction"},
    {"course_id": "C002", "title": "Deep Learning Specialization", "provider": "Coursera (DeepLearning.AI)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 80, "price_usd": 49.00, "skills_covered": "CNNs; RNNs; Transformers; TensorFlow; Optimization", "prerequisites": "Python; Linear Algebra; Basic ML", "description": "Master deep learning and neural network architectures from fundamentals to sequence models.", "url": "https://www.coursera.org/specializations/deep-learning"},
    {"course_id": "C003", "title": "CS50's Introduction to Computer Science", "provider": "edX (Harvard)", "category": "Computer Science", "level": "Beginner", "rating": 4.9, "duration_hours": 100, "price_usd": 0.00, "skills_covered": "C; Python; SQL; Algorithms; Data Structures; Memory Management", "prerequisites": "None", "description": "Harvard University's flagship introduction to computer science and programming methodologies.", "url": "https://www.edx.org/course/cs50s-introduction-to-computer-science"},
    {"course_id": "C004", "title": "CS50's Introduction to Artificial Intelligence with Python", "provider": "edX (Harvard)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 70, "price_usd": 0.00, "skills_covered": "Graph Search; Minimax; Reinforcement Learning; NLP; Markov Models", "prerequisites": "Python", "description": "Explore concepts and algorithms at the foundation of modern artificial intelligence.", "url": "https://www.edx.org/course/cs50s-introduction-to-artificial-intelligence-with-python"},
    {"course_id": "C005", "title": "Full Stack Open 2024", "provider": "University of Helsinki", "category": "Web Development", "level": "Intermediate", "rating": 4.9, "duration_hours": 120, "price_usd": 0.00, "skills_covered": "React; Node.js; Express; MongoDB; GraphQL; TypeScript; Docker", "prerequisites": "JavaScript Basics", "description": "Deep dive into modern JavaScript-based web development covering single page applications and REST APIs.", "url": "https://fullstackopen.com/"},
    {"course_id": "C006", "title": "The Complete 2024 Web Development Bootcamp", "provider": "Udemy (Dr. Angela Yu)", "category": "Web Development", "level": "Beginner", "rating": 4.8, "duration_hours": 65, "price_usd": 19.99, "skills_covered": "HTML5; CSS3; JavaScript; React; Node.js; PostgreSQL; Web3", "prerequisites": "None", "description": "Comprehensive bootcamp covering frontend and backend technologies through real-world projects.", "url": "https://www.udemy.com/course/the-complete-web-development-bootcamp/"},
    {"course_id": "C007", "title": "Fast.ai: Practical Deep Learning for Coders", "provider": "Fast.ai", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.9, "duration_hours": 50, "price_usd": 0.00, "skills_covered": "PyTorch; Fastai; Computer Vision; NLP; Model Deployment", "prerequisites": "Python", "description": "Hands-on top-down deep learning course teaching modern neural network techniques for practical problems.", "url": "https://course.fast.ai/"},
    {"course_id": "C008", "title": "Google Data Analytics Professional Certificate", "provider": "Coursera (Google)", "category": "Data Science", "level": "Beginner", "rating": 4.8, "duration_hours": 180, "price_usd": 49.00, "skills_covered": "Spreadsheets; SQL; Tableau; R Programming; Data Cleaning", "prerequisites": "None", "description": "Gain in-demand skills that lead to an entry-level job in data analytics with no degree needed.", "url": "https://www.coursera.org/professional-certificates/google-data-analytics"},
    {"course_id": "C009", "title": "IBM Data Science Professional Certificate", "provider": "Coursera (IBM)", "category": "Data Science", "level": "Beginner", "rating": 4.7, "duration_hours": 160, "price_usd": 49.00, "skills_covered": "Python; SQL; Data Analysis; Data Visualization; Machine Learning", "prerequisites": "Basic Math", "description": "Kickstart your career in data science with practical labs in Python and Jupyter Notebooks.", "url": "https://www.coursera.org/professional-certificates/ibm-data-science"},
    {"course_id": "C010", "title": "Docker and Kubernetes: The Complete Guide", "provider": "Udemy (Stephen Grider)", "category": "Cloud & DevOps", "level": "Intermediate", "rating": 4.8, "duration_hours": 24, "price_usd": 19.99, "skills_covered": "Docker; Kubernetes; Container Orchestration; CI/CD; AWS Deployment", "prerequisites": "Basic Terminal", "description": "Build test and deploy Docker-based applications using Kubernetes on production cloud clusters.", "url": "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/"},
    {"course_id": "C011", "title": "AWS Certified Solutions Architect Associate (SAA-C03)", "provider": "Udemy (Stephane Maarek)", "category": "Cloud & DevOps", "level": "Intermediate", "rating": 4.8, "duration_hours": 28, "price_usd": 19.99, "skills_covered": "AWS EC2; S3; VPC; IAM; Lambda; CloudFront; Cloud Architecture", "prerequisites": "Basic IT Concepts", "description": "Comprehensive exam preparation covering core AWS cloud services and best architectural practices.", "url": "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/"},
    {"course_id": "C012", "title": "Google Cloud Associate Cloud Engineer", "provider": "Coursera (Google Cloud)", "category": "Cloud & DevOps", "level": "Intermediate", "rating": 4.7, "duration_hours": 40, "price_usd": 49.00, "skills_covered": "GCP Compute Engine; Cloud Storage; GKE; IAM; Cloud SQL", "prerequisites": "Cloud Fundamentals", "description": "Prepare for the GCP Associate Cloud Engineer certification with guided labs on Qwiklabs.", "url": "https://www.coursera.org/professional-certificates/google-cloud-associate-cloud-engineer"},
    {"course_id": "C013", "title": "The Complete JavaScript Course: From Zero to Expert", "provider": "Udemy (Jonas Schmedtmann)", "category": "Web Development", "level": "Beginner", "rating": 4.8, "duration_hours": 68, "price_usd": 19.99, "skills_covered": "JavaScript; ES6+; DOM; Asynchronous JS; OOP; Webpack", "prerequisites": "None", "description": "Master modern JavaScript with projects challenges theory and complete coding exercises.", "url": "https://www.udemy.com/course/the-complete-javascript-course/"},
    {"course_id": "C014", "title": "React - The Complete Guide (incl. Next.js and Redux)", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 50, "price_usd": 19.99, "skills_covered": "React; Hooks; Redux Toolkit; Next.js; TypeScript; SPA", "prerequisites": "HTML CSS JS", "description": "Dive in and learn React.js from scratch including Redux Hooks and Next.js fullstack features.", "url": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/"},
    {"course_id": "C015", "title": "Natural Language Processing Specialization", "provider": "Coursera (DeepLearning.AI)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.7, "duration_hours": 60, "price_usd": 49.00, "skills_covered": "NLP; Word2Vec; Sentiment Analysis; Transformers; Attention; HuggingFace", "prerequisites": "Python; Deep Learning", "description": "Build NLP applications using sentiment analysis machine translation and question answering models.", "url": "https://www.coursera.org/specializations/natural-language-processing-nlp"},
    {"course_id": "C016", "title": "Generative AI with Large Language Models", "provider": "Coursera (DeepLearning.AI & AWS)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 20, "price_usd": 49.00, "skills_covered": "LLMs; Transformers; Prompt Engineering; PEFT; LoRA; RLHF; LangChain", "prerequisites": "Python; Deep Learning", "description": "Understand LLM lifecycle from pre-training to fine-tuning and deployment for generative apps.", "url": "https://www.coursera.org/learn/generative-ai-with-llms"},
    {"course_id": "C017", "title": "Hugging Face NLP Course", "provider": "Hugging Face", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.9, "duration_hours": 30, "price_usd": 0.00, "skills_covered": "Hugging Face Transformers; Tokenizers; Datasets; Model Hub; Fine-tuning", "prerequisites": "PyTorch or TensorFlow", "description": "Comprehensive hands-on guide to mastering state-of-the-art Natural Language Processing with transformers.", "url": "https://huggingface.co/learn/nlp-course/"},
    {"course_id": "C018", "title": "Applied Data Science with Python Specialization", "provider": "Coursera (University of Michigan)", "category": "Data Science", "level": "Intermediate", "rating": 4.6, "duration_hours": 100, "price_usd": 49.00, "skills_covered": "Pandas; Matplotlib; Scikit-Learn; NLTK; NetworkX; Social Network Analysis", "prerequisites": "Python Basics", "description": "Gain expertise in analyzing and visualizing real-world data using Python scientific libraries.", "url": "https://www.coursera.org/specializations/data-science-python"},
    {"course_id": "C019", "title": "Mathematics for Machine Learning Specialization", "provider": "Coursera (Imperial College London)", "category": "AI & Machine Learning", "level": "Beginner", "rating": 4.7, "duration_hours": 60, "price_usd": 49.00, "skills_covered": "Linear Algebra; Multivariate Calculus; PCA; Eigenvalues; Optimization", "prerequisites": "High School Math", "description": "Bridge the gap between pure mathematics and core practical machine learning algorithms.", "url": "https://www.coursera.org/specializations/mathematics-machine-learning"},
    {"course_id": "C020", "title": "Introduction to Cybersecurity Tools & Cyber Attacks", "provider": "Coursera (IBM)", "category": "Cybersecurity", "level": "Beginner", "rating": 4.6, "duration_hours": 20, "price_usd": 49.00, "skills_covered": "Cyber Threats; Network Security; Cryptography; Firewalls; Incident Response", "prerequisites": "Basic IT Knowledge", "description": "Learn foundational cybersecurity concepts incident management and common attack vectors.", "url": "https://www.coursera.org/learn/introduction-cyber-security-tools-cyber-attacks"},
    {"course_id": "C021", "title": "CompTIA Security+ (SY0-701) Complete Course", "provider": "Udemy (Jason Dion)", "category": "Cybersecurity", "level": "Intermediate", "rating": 4.7, "duration_hours": 32, "price_usd": 19.99, "skills_covered": "Threats; Vulnerabilities; Identity Management; Security Architecture; Cryptography", "prerequisites": "Networking Basics", "description": "All-in-one preparation course for CompTIA Security+ certification covering defense-in-depth.", "url": "https://www.udemy.com/course/security-plus/"},
    {"course_id": "C022", "title": "The Complete Ethical Hacking Bootcamp", "provider": "Udemy (Zaid Sabih)", "category": "Cybersecurity", "level": "Beginner", "rating": 4.7, "duration_hours": 25, "price_usd": 19.99, "skills_covered": "Kali Linux; Penetration Testing; Wireshark; Metasploit; Web Hacking", "prerequisites": "None", "description": "Learn ethical hacking penetration testing and network protection through hands-on virtual labs.", "url": "https://www.udemy.com/course/learn-ethical-hacking-from-scratch/"},
    {"course_id": "C023", "title": "Google IT Automation with Python Professional Certificate", "provider": "Coursera (Google)", "category": "Software Engineering", "level": "Beginner", "rating": 4.7, "duration_hours": 120, "price_usd": 49.00, "skills_covered": "Python; Git; GitHub; Automation; Linux; Bash; Troubleshooting", "prerequisites": "None", "description": "Learn how to automate system administration tasks and manage cloud resources using Python.", "url": "https://www.coursera.org/professional-certificates/google-it-automation"},
    {"course_id": "C024", "title": "Missing Semester of Your CS Education", "provider": "MIT", "category": "Computer Science", "level": "Beginner", "rating": 4.9, "duration_hours": 25, "price_usd": 0.00, "skills_covered": "Vim; Git; Bash; Shell Scripting; SSH; Command Line Tools; Debugging", "prerequisites": "None", "description": "Learn the practical computing tools every computer science student should know but is rarely taught.", "url": "https://missing.csail.mit.edu/"},
    {"course_id": "C025", "title": "Design Patterns in Python", "provider": "Udemy (Dmitri Nesteruk)", "category": "Software Engineering", "level": "Intermediate", "rating": 4.6, "duration_hours": 12, "price_usd": 19.99, "skills_covered": "Creational Patterns; Structural Patterns; Behavioral Patterns; SOLID Principles", "prerequisites": "Python", "description": "Discover modern implementation of classic Gang of Four design patterns in idiomatic Python.", "url": "https://www.udemy.com/course/design-patterns-python/"},
    {"course_id": "C026", "title": "Data Structures and Algorithms Specialization", "provider": "Coursera (UC San Diego)", "category": "Computer Science", "level": "Intermediate", "rating": 4.7, "duration_hours": 150, "price_usd": 49.00, "skills_covered": "Sorting; Trees; Graphs; Dynamic Programming; NP-Completeness; String Algorithms", "prerequisites": "One Programming Language", "description": "Master algorithmic programming techniques to ace software engineering technical interviews.", "url": "https://www.coursera.org/specializations/data-structures-algorithms"},
    {"course_id": "C027", "title": "Flutter & Dart - The Complete Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Mobile Development", "level": "Beginner", "rating": 4.6, "duration_hours": 30, "price_usd": 19.99, "skills_covered": "Flutter; Dart; Mobile UI; State Management; REST APIs; Firebase", "prerequisites": "None", "description": "A complete guide to building native iOS and Android apps using Google's Flutter framework.", "url": "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/"},
    {"course_id": "C028", "title": "iOS & Swift - The Complete iOS App Development Bootcamp", "provider": "Udemy (Dr. Angela Yu)", "category": "Mobile Development", "level": "Beginner", "rating": 4.8, "duration_hours": 60, "price_usd": 19.99, "skills_covered": "Swift; SwiftUI; CoreData; ARKit; iOS Architecture; Git", "prerequisites": "None", "description": "Master Swift and iOS development by building 15+ real-world apps from scratch.", "url": "https://www.udemy.com/course/ios-13-app-development-bootcamp/"},
    {"course_id": "C029", "title": "Android Basics in Kotlin", "provider": "Google Developers", "category": "Mobile Development", "level": "Beginner", "rating": 4.8, "duration_hours": 40, "price_usd": 0.00, "skills_covered": "Kotlin; Android Studio; ViewModel; Navigation; Room DB; Coroutines", "prerequisites": "None", "description": "Learn foundational Android development concepts and build Android apps using Kotlin.", "url": "https://developer.android.com/courses/android-basics-kotlin/course"},
    {"course_id": "C030", "title": "Google UX Design Professional Certificate", "provider": "Coursera (Google)", "category": "UI/UX Design", "level": "Beginner", "rating": 4.8, "duration_hours": 140, "price_usd": 49.00, "skills_covered": "Figma; Wireframing; Prototyping; User Research; Usability Testing", "prerequisites": "None", "description": "Complete training to become a job-ready UX designer through building an end-to-end portfolio.", "url": "https://www.coursera.org/professional-certificates/google-ux-design"},
    {"course_id": "C031", "title": "User Experience Research and Design Specialization", "provider": "Coursera (University of Michigan)", "category": "UI/UX Design", "level": "Intermediate", "rating": 4.7, "duration_hours": 50, "price_usd": 49.00, "skills_covered": "User Research; Heuristic Evaluation; Information Architecture; Interaction Design", "prerequisites": "None", "description": "Learn how to design great user experiences through research prototyping and usability testing.", "url": "https://www.coursera.org/specializations/michiganux"},
    {"course_id": "C032", "title": "Figma UI UX Design Essentials", "provider": "Udemy (Daniel Walter Scott)", "category": "UI/UX Design", "level": "Beginner", "rating": 4.7, "duration_hours": 12, "price_usd": 19.99, "skills_covered": "Figma; Auto Layout; Design Systems; Micro-interactions; Responsive Design", "prerequisites": "None", "description": "Use Figma to design modern mobile apps and website user interfaces with animations and prototypes.", "url": "https://www.udemy.com/course/figma-ui-ux-design-essentials/"},
    {"course_id": "C033", "title": "System Design Interview - An Insider's Guide", "provider": "ByteByteGo (Alex Xu)", "category": "Software Engineering", "level": "Advanced", "rating": 4.9, "duration_hours": 35, "price_usd": 79.00, "skills_covered": "Scalability; Microservices; Caching; Load Balancing; Database Sharding; Kafka", "prerequisites": "Backend Fundamentals", "description": "Comprehensive guide to passing complex software architecture and distributed system interviews.", "url": "https://bytebytego.com/"},
    {"course_id": "C034", "title": "Distributed Systems", "provider": "MIT OCW (6.824)", "category": "Software Engineering", "level": "Advanced", "rating": 4.9, "duration_hours": 80, "price_usd": 0.00, "skills_covered": "Raft; Paxos; MapReduce; Fault Tolerance; Consistency; Go", "prerequisites": "Strong Systems Programming", "description": "Legendary MIT course covering the principles and abstractions of fault-tolerant distributed systems.", "url": "https://pdos.csail.mit.edu/6.824/"},
    {"course_id": "C035", "title": "Reinforcement Learning Specialization", "provider": "Coursera (University of Alberta)", "category": "AI & Machine Learning", "level": "Advanced", "rating": 4.7, "duration_hours": 60, "price_usd": 49.00, "skills_covered": "Q-Learning; Policy Gradients; Markov Decision Processes; Actor-Critic; Bellman Equations", "prerequisites": "Python; Calculus; Probability", "description": "Master the algorithms and theoretical frameworks of Reinforcement Learning taught by pioneers.", "url": "https://www.coursera.org/specializations/reinforcement-learning-specialization"},
    {"course_id": "C036", "title": "Machine Learning Engineering for Production (MLOps)", "provider": "Coursera (DeepLearning.AI)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.7, "duration_hours": 45, "price_usd": 49.00, "skills_covered": "MLOps; Data Pipelines; Model Monitoring; CI/CD for ML; TFX; MLflow", "prerequisites": "Machine Learning; Python", "description": "Learn how to design scalable and production-ready machine learning systems and pipelines.", "url": "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops"},
    {"course_id": "C037", "title": "Data Engineering on GCP Specialization", "provider": "Coursera (Google Cloud)", "category": "Data Science", "level": "Intermediate", "rating": 4.6, "duration_hours": 50, "price_usd": 49.00, "skills_covered": "BigQuery; Dataflow; Cloud Pub/Sub; Dataproc; Apache Beam", "prerequisites": "SQL; Python", "description": "Learn how to design build and operationalize data processing systems on Google Cloud Platform.", "url": "https://www.coursera.org/specializations/gcp-data-engineering"},
    {"course_id": "C038", "title": "Data Engineering with AWS", "provider": "Udemy (Stephane Maarek)", "category": "Data Science", "level": "Intermediate", "rating": 4.7, "duration_hours": 25, "price_usd": 19.99, "skills_covered": "AWS Glue; Athena; Redshift; EMR; Kinesis; QuickSight; S3 Data Lake", "prerequisites": "AWS Basics", "description": "Master AWS data analytics and data engineering services to build robust cloud data pipelines.", "url": "https://www.udemy.com/course/aws-data-analytics/"},
    {"course_id": "C039", "title": "Prompt Engineering for Generative AI", "provider": "Vanderbilt University (Coursera)", "category": "AI & Machine Learning", "level": "Beginner", "rating": 4.8, "duration_hours": 18, "price_usd": 49.00, "skills_covered": "Prompt Engineering; Few-Shot Learning; Chain of Thought; ReAct; LLM Constraints", "prerequisites": "None", "description": "Learn prompt engineering techniques to elicit optimal reasoning and responses from LLMs.", "url": "https://www.coursera.org/learn/prompt-engineering"},
    {"course_id": "C040", "title": "LangChain & Vector Databases in Production", "provider": "Activeloop & Towards AI", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 20, "price_usd": 0.00, "skills_covered": "LangChain; Vector Search; ChromaDB; Pinecone; RAG; Embeddings", "prerequisites": "Python Basics", "description": "Build LLM-powered autonomous agents and Retrieval Augmented Generation (RAG) applications.", "url": "https://learn.activeloop.ai/courses/langchain"},
    {"course_id": "C041", "title": "Complete SQL Bootcamp: Go from Zero to Hero", "provider": "Udemy (Jose Portilla)", "category": "Data Science", "level": "Beginner", "rating": 4.7, "duration_hours": 12, "price_usd": 19.99, "skills_covered": "PostgreSQL; SQL Queries; Joins; Aggregations; Window Functions; Subqueries", "prerequisites": "None", "description": "Master SQL and relational database queries through practical business analytics exercises.", "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/"},
    {"course_id": "C042", "title": "PostgreSQL for Everybody Specialization", "provider": "Coursera (University of Michigan)", "category": "Data Science", "level": "Beginner", "rating": 4.7, "duration_hours": 40, "price_usd": 49.00, "skills_covered": "PostgreSQL; Database Design; Normalization; JSONB; Elasticsearch", "prerequisites": "Python Basics", "description": "Learn database design relational queries and data modeling using PostgreSQL.", "url": "https://www.coursera.org/specializations/postgresql-for-everybody"},
    {"course_id": "C043", "title": "Go: The Complete Developer's Guide (Golang)", "provider": "Udemy (Stephen Grider)", "category": "Software Engineering", "level": "Beginner", "rating": 4.7, "duration_hours": 10, "price_usd": 19.99, "skills_covered": "Go; Concurrency; Goroutines; Channels; Interfaces; HTTP Servers", "prerequisites": "Basic Programming", "description": "Master the fundamentals of Google's Go programming language with practical concurrency projects.", "url": "https://www.udemy.com/course/go-the-complete-developers-guide/"},
    {"course_id": "C044", "title": "Rust Programming: The Complete Guide", "provider": "Udemy (Nathan Stocks)", "category": "Software Engineering", "level": "Intermediate", "rating": 4.7, "duration_hours": 15, "price_usd": 19.99, "skills_covered": "Rust; Memory Safety; Ownership; Lifetimes; Concurrency; Cargo", "prerequisites": "C or C++ or Python", "description": "Master safe systems programming and modern memory management using the Rust programming language.", "url": "https://www.udemy.com/course/ultimate-rust-crash-course/"},
    {"course_id": "C045", "title": "DevOps Beginners to Advanced with Projects", "provider": "Udemy (Imran Teli)", "category": "Cloud & DevOps", "level": "Beginner", "rating": 4.6, "duration_hours": 35, "price_usd": 19.99, "skills_covered": "Linux; Jenkins; Git; Ansible; Docker; Kubernetes; Terraform", "prerequisites": "None", "description": "Comprehensive real-world DevOps journey from server setup to automated CI/CD deployment pipelines.", "url": "https://www.udemy.com/course/decodingdevops/"},
    {"course_id": "C046", "title": "Terraform for AWS - Associate 003", "provider": "Udemy (Zeal Vora)", "category": "Cloud & DevOps", "level": "Intermediate", "rating": 4.7, "duration_hours": 16, "price_usd": 19.99, "skills_covered": "Infrastructure as Code; Terraform; AWS; State Management; Modules", "prerequisites": "AWS Basics", "description": "Automate cloud infrastructure provisioning on Amazon Web Services using HashiCorp Terraform.", "url": "https://www.udemy.com/course/terraform-certified/"},
    {"course_id": "C047", "title": "Kubernetes for Certified Kubernetes Administrator (CKA)", "provider": "Udemy (Mumshad Mannambeth)", "category": "Cloud & DevOps", "level": "Advanced", "rating": 4.8, "duration_hours": 22, "price_usd": 19.99, "skills_covered": "Kubernetes Architecture; Networking; Storage; Security; Troubleshooting; ETCD", "prerequisites": "Docker Basics", "description": "In-depth hands-on exam prep for Kubernetes cluster administration with interactive coding labs.", "url": "https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/"},
    {"course_id": "C048", "title": "Next.js 14 & React - The Complete Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Web Development", "level": "Intermediate", "rating": 4.8, "duration_hours": 32, "price_usd": 19.99, "skills_covered": "Next.js; Server Actions; App Router; SSR; SSG; SEO; Tailwind CSS", "prerequisites": "React Basics", "description": "Build modern fullstack production-grade web applications using Next.js App Router and React.", "url": "https://www.udemy.com/course/nextjs-react-the-complete-guide/"},
    {"course_id": "C049", "title": "Tailwind CSS From Scratch", "provider": "Udemy (Brad Traversy)", "category": "Web Development", "level": "Beginner", "rating": 4.8, "duration_hours": 12, "price_usd": 19.99, "skills_covered": "Tailwind CSS; Responsive Design; Flexbox; CSS Grid; Modern UI", "prerequisites": "HTML CSS", "description": "Build beautiful responsive web user interfaces quickly without writing custom vanilla CSS.", "url": "https://www.udemy.com/course/tailwind-css-from-scratch/"},
    {"course_id": "C050", "title": "TypeScript for Professionals", "provider": "Frontend Masters (Mike North)", "category": "Web Development", "level": "Intermediate", "rating": 4.9, "duration_hours": 14, "price_usd": 39.00, "skills_covered": "TypeScript; Generics; Type Guards; Conditional Types; Compilation", "prerequisites": "JavaScript", "description": "Level up your JavaScript skills by adding static typing robustness and enterprise scalability.", "url": "https://frontendmasters.com/courses/typescript-v4/"},
    {"course_id": "C051", "title": "Building Systems with the ChatGPT API", "provider": "DeepLearning.AI", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 6, "price_usd": 0.00, "skills_covered": "LLM Workflows; Chain of Thought; Moderation; System Prompts; Evaluation", "prerequisites": "Python", "description": "Learn how to build complex multi-step automated applications using OpenAI's ChatGPT APIs.", "url": "https://www.deeplearning.ai/short-courses/building-systems-with-chatgpt/"},
    {"course_id": "C052", "title": "AI Agents in LangGraph", "provider": "DeepLearning.AI & LangChain", "category": "AI & Machine Learning", "level": "Advanced", "rating": 4.9, "duration_hours": 8, "price_usd": 0.00, "skills_covered": "LangGraph; Multi-Agent Workflows; Human-in-the-loop; State Machines; Tool Calling", "prerequisites": "Python; LangChain", "description": "Build controllable cyclical multi-agent workflows and autonomous agents using LangGraph.", "url": "https://www.deeplearning.ai/short-courses/ai-agents-in-langgraph/"},
    {"course_id": "C053", "title": "CrewAI: Multi-Agent Systems", "provider": "DeepLearning.AI & CrewAI", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 6, "price_usd": 0.00, "skills_covered": "CrewAI; Multi-Agent Collaboration; Role Playing; Sequential Pipelines; Delegation", "prerequisites": "Python Basics", "description": "Design and coordinate teams of specialized AI agents to automate end-to-end knowledge workflows.", "url": "https://www.deeplearning.ai/short-courses/multi-agent-systems-with-crewai/"},
    {"course_id": "C054", "title": "Microservices Architecture with Spring Boot", "provider": "Udemy (In28Minutes)", "category": "Software Engineering", "level": "Intermediate", "rating": 4.6, "duration_hours": 22, "price_usd": 19.99, "skills_covered": "Spring Boot; Spring Cloud; Docker; Eureka; API Gateway; Resilience4j", "prerequisites": "Java Basics", "description": "Develop robust cloud-native RESTful microservices using Spring Boot and Spring Cloud tooling.", "url": "https://www.udemy.com/course/microservices-with-spring-boot-and-spring-cloud/"},
    {"course_id": "C055", "title": "Core Java Specialization", "provider": "Coursera (LearnQuest)", "category": "Software Engineering", "level": "Beginner", "rating": 4.7, "duration_hours": 60, "price_usd": 49.00, "skills_covered": "Java; Object-Oriented Programming; Collections; Multithreading; Exception Handling", "prerequisites": "None", "description": "Foundational guide to Java programming principles algorithms and application architecture.", "url": "https://www.coursera.org/specializations/core-java"},
    {"course_id": "C056", "title": "C++ Programming for Game Development", "provider": "Udemy (Stephen Ulibarri)", "category": "Software Engineering", "level": "Intermediate", "rating": 4.8, "duration_hours": 40, "price_usd": 19.99, "skills_covered": "C++; Pointers; Memory Management; Unreal Engine 5; OOP; Game Math", "prerequisites": "Basic Programming", "description": "Master modern C++ mechanics and object-oriented paradigms tailored for 3D game engines.", "url": "https://www.udemy.com/course/unreal-engine-5-the-ultimate-game-developer-course/"},
    {"course_id": "C057", "title": "Blockchain Basics Specialization", "provider": "Coursera (University at Buffalo)", "category": "Computer Science", "level": "Beginner", "rating": 4.6, "duration_hours": 35, "price_usd": 49.00, "skills_covered": "Blockchain; Smart Contracts; Ethereum; Cryptography; Consensus Algorithms", "prerequisites": "None", "description": "Learn the decentralized foundations smart contract principles and architectures of blockchain systems.", "url": "https://www.coursera.org/specializations/blockchain"},
    {"course_id": "C058", "title": "Ethereum and Solidity: The Complete Developer's Guide", "provider": "Udemy (Stephen Grider)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 24, "price_usd": 19.99, "skills_covered": "Solidity; Ethereum; Web3.js; Smart Contracts; Truffle; Metamask", "prerequisites": "JavaScript", "description": "Build secure decentralized applications (DApps) on Ethereum using Solidity and smart contracts.", "url": "https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/"},
    {"course_id": "C059", "title": "Cybersecurity Operations (CyberOps) Associate", "provider": "Cisco Networking Academy", "category": "Cybersecurity", "level": "Intermediate", "rating": 4.7, "duration_hours": 70, "price_usd": 0.00, "skills_covered": "Security Operations Center; SIEM; Intrusion Detection; Incident Analysis; Threat Intelligence", "prerequisites": "Networking Basics", "description": "Hands-on training preparing security analysts for monitoring and defending enterprise networks.", "url": "https://www.netacad.com/courses/cybersecurity/cyberops-associate"},
    {"course_id": "C060", "title": "Web Security & Bug Bounty: Learn Pentesting", "provider": "Udemy (Andrei Neagoie)", "category": "Cybersecurity", "level": "Intermediate", "rating": 4.7, "duration_hours": 12, "price_usd": 19.99, "skills_covered": "XSS; SQL Injection; CSRF; SSRF; OWASP Top 10; Burp Suite", "prerequisites": "Web Basics", "description": "Discover web vulnerabilities exploit weaknesses ethically and secure modern web architectures.", "url": "https://www.udemy.com/course/web-security-bug-bounty-learn-penetration-testing/"},
    {"course_id": "C061", "title": "Computer Networking: A Top-Down Approach", "provider": "Stanford Online / edX", "category": "Computer Science", "level": "Beginner", "rating": 4.8, "duration_hours": 45, "price_usd": 0.00, "skills_covered": "TCP/IP; DNS; HTTP; Routing Protocols; Sockets; Congestion Control", "prerequisites": "Basic CS", "description": "Understand internet architecture protocols packet switching and end-to-end communication.", "url": "https://online.stanford.edu/courses/soe-ynetwork-computer-networking"},
    {"course_id": "C062", "title": "Operating Systems: Three Easy Pieces (OSTEP)", "provider": "University of Wisconsin-Madison", "category": "Computer Science", "level": "Intermediate", "rating": 4.9, "duration_hours": 60, "price_usd": 0.00, "skills_covered": "Virtualization; Concurrency; Persistence; CPU Scheduling; Paging; File Systems", "prerequisites": "C Programming", "description": "The definitive guide to operating system internals virtualization scheduling and storage.", "url": "https://pages.cs.wisc.edu/~remzi/OSTEP/"},
    {"course_id": "C063", "title": "Data Engineering Zoomcamp", "provider": "DataTalks.Club", "category": "Data Science", "level": "Intermediate", "rating": 4.9, "duration_hours": 80, "price_usd": 0.00, "skills_covered": "Docker; SQL; Terraform; GCP; Mage; dbt; Spark; Kafka", "prerequisites": "Python & SQL", "description": "Free 9-week intensive bootcamp covering batch streaming data pipelines and cloud data warehousing.", "url": "https://github.com/DataTalksClub/data-engineering-zoomcamp"},
    {"course_id": "C064", "title": "Machine Learning Zoomcamp", "provider": "DataTalks.Club", "category": "Data Science", "level": "Intermediate", "rating": 4.8, "duration_hours": 60, "price_usd": 0.00, "skills_covered": "Regression; Classification; Deployment; Docker; KServe; Kubeflow; AWS Lambda", "prerequisites": "Python Basics", "description": "Practical project-oriented machine learning course focused on end-to-end model deployment.", "url": "https://github.com/DataTalksClub/machine-learning-zoomcamp"},
    {"course_id": "C065", "title": "LLM Zoomcamp: Generative AI & Engineering", "provider": "DataTalks.Club", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.9, "duration_hours": 50, "price_usd": 0.00, "skills_covered": "RAG; Vector Search; Elasticsearch; Ollama; Evaluation; LLM Monitoring", "prerequisites": "Python", "description": "Learn how to build real-world production-ready Retrieval-Augmented Generation applications.", "url": "https://github.com/DataTalksClub/llm-zoomcamp"},
    {"course_id": "C066", "title": "Statistics for Data Science and Business Analysis", "provider": "Udemy (365 Careers)", "category": "Data Science", "level": "Beginner", "rating": 4.6, "duration_hours": 10, "price_usd": 19.99, "skills_covered": "Descriptive Statistics; Inferential Statistics; Hypothesis Testing; Regression; ANOVA", "prerequisites": "High School Math", "description": "Master fundamental statistical concepts and apply hypothesis testing to real-world business problems.", "url": "https://www.udemy.com/course/statistics-for-data-science-and-business-analysis/"},
    {"course_id": "C067", "title": "Tableau 2024 A-Z: Hands-On Data Visualization", "provider": "Udemy (Kirill Eremenko)", "category": "Data Science", "level": "Beginner", "rating": 4.6, "duration_hours": 9, "price_usd": 19.99, "skills_covered": "Tableau; Data Storytelling; Interactive Dashboards; Business Intelligence; Calculations", "prerequisites": "None", "description": "Learn data visualization and dashboard design using Tableau to turn numbers into visual stories.", "url": "https://www.udemy.com/course/tableau10/"},
    {"course_id": "C068", "title": "Power BI Masterclass - Dashboards and Power Query", "provider": "Udemy (Nikolai Schuler)", "category": "Data Science", "level": "Beginner", "rating": 4.6, "duration_hours": 8, "price_usd": 19.99, "skills_covered": "Power BI; DAX; Power Query; Data Modeling; KPI Dashboards", "prerequisites": "Excel Basics", "description": "Transform raw enterprise data into interactive business reports and dashboards with Power BI.", "url": "https://www.udemy.com/course/power-bi-masterclass-dashboards-and-power-query/"},
    {"course_id": "C069", "title": "Linear Algebra Done Right", "provider": "MIT OpenCourseWare (Gilbert Strang)", "category": "Computer Science", "level": "Intermediate", "rating": 4.9, "duration_hours": 45, "price_usd": 0.00, "skills_covered": "Matrix Multiplication; Vector Spaces; Orthogonality; SVD; Eigenvectors", "prerequisites": "Calculus", "description": "World-renowned introduction to linear algebra matrix factorizations and foundational applications.", "url": "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/"},
    {"course_id": "C070", "title": "Product Management Fundamentals", "provider": "Coursera (University of Virginia)", "category": "UI/UX Design", "level": "Beginner", "rating": 4.7, "duration_hours": 15, "price_usd": 49.00, "skills_covered": "Product Strategy; User Personas; MVP; Agile; Roadmapping; Metrics", "prerequisites": "None", "description": "Master the core frameworks required to manage digital products from inception to market launch.", "url": "https://www.coursera.org/learn/uva-darden-digital-product-management"},
    {"course_id": "C071", "title": "Agile with Atlassian Jira", "provider": "Coursera (Atlassian)", "category": "Software Engineering", "level": "Beginner", "rating": 4.7, "duration_hours": 12, "price_usd": 49.00, "skills_covered": "Scrum; Kanban; Jira; Sprints; Agile Estimation; Backlog Grooming", "prerequisites": "None", "description": "Learn Agile project management principles and configure Jira boards to deliver software iteratively.", "url": "https://www.coursera.org/learn/agile-atlassian-jira"},
    {"course_id": "C072", "title": "Computer Vision Nanodegree", "provider": "Udacity", "category": "AI & Machine Learning", "level": "Advanced", "rating": 4.7, "duration_hours": 80, "price_usd": 399.00, "skills_covered": "OpenCV; YOLO; Object Detection; Image Segmentation; SLAM; GANs", "prerequisites": "Python; Deep Learning", "description": "Master computer vision workflows from image processing with OpenCV to real-time object tracking.", "url": "https://www.udacity.com/course/computer-vision-nanodegree--nd131"},
    {"course_id": "C073", "title": "Autonomous Vehicles Foundations", "provider": "Coursera (University of Toronto)", "category": "AI & Machine Learning", "level": "Advanced", "rating": 4.8, "duration_hours": 50, "price_usd": 49.00, "skills_covered": "Kalman Filters; Localization; Motion Planning; CARLA Simulator; LiDAR", "prerequisites": "Python; Physics; Linear Algebra", "description": "Understand state estimation localization perception and path planning algorithms for autonomous driving.", "url": "https://www.coursera.org/specializations/self-driving-cars"},
    {"course_id": "C074", "title": "Linux Command Line and Shell Scripting Bootcamp", "provider": "Udemy (Colt Steele)", "category": "Software Engineering", "level": "Beginner", "rating": 4.8, "duration_hours": 18, "price_usd": 19.99, "skills_covered": "Linux CLI; Bash; Permissions; Cron; Sed; Awk; Grep; Process Management", "prerequisites": "None", "description": "Master the Linux command line file systems process management and write powerful shell scripts.", "url": "https://www.udemy.com/course/the-linux-command-line-bootcamp/"},
    {"course_id": "C075", "title": "Git and GitHub - The Practical Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Software Engineering", "level": "Beginner", "rating": 4.8, "duration_hours": 11, "price_usd": 19.99, "skills_covered": "Git; GitHub; Branching; Merging; Rebasing; Conflict Resolution; CI/CD", "prerequisites": "None", "description": "Master version control workflows team collaboration merge conflict resolution and pull requests.", "url": "https://www.udemy.com/course/git-github-the-practical-guide/"},
    {"course_id": "C076", "title": "FastAPI - The Complete Course", "provider": "Udemy (Eric Roby)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 16, "price_usd": 19.99, "skills_covered": "FastAPI; Pydantic; SQLAlchemy; JWT Authentication; Async Python; Swagger UI", "prerequisites": "Python Basics", "description": "Build high-performance asynchronous REST APIs in Python using FastAPI Pydantic and SQLite/PostgreSQL.", "url": "https://www.udemy.com/course/fastapi-the-complete-course/"},
    {"course_id": "C077", "title": "Django 5 - The Practical Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 23, "price_usd": 19.99, "skills_covered": "Django; ORM; Django Templates; Admin; User Authentication; Postgres", "prerequisites": "Python Basics", "description": "Build practical full-stack web applications with Python using the production-proven Django framework.", "url": "https://www.udemy.com/course/practical-django-the-complete-guide/"},
    {"course_id": "C078", "title": "Node.js Express MongoDB & More: The Complete Bootcamp", "provider": "Udemy (Jonas Schmedtmann)", "category": "Web Development", "level": "Intermediate", "rating": 4.8, "duration_hours": 42, "price_usd": 19.99, "skills_covered": "Node.js; Express; MongoDB; Mongoose; JWT; Stripe; REST APIs", "prerequisites": "JavaScript Basics", "description": "Master backend web development building real-world enterprise applications with Node and Mongo.", "url": "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/"},
    {"course_id": "C079", "title": "GraphQL with React: The Complete Developers Guide", "provider": "Udemy (Stephen Grider)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 14, "price_usd": 19.99, "skills_covered": "GraphQL; Apollo Client; Express GraphQL; Schemas; Mutations; Queries", "prerequisites": "React Basics", "description": "Learn how to design scalable GraphQL schemas and query backend APIs seamlessly from React.", "url": "https://www.udemy.com/course/graphql-with-react-course/"},
    {"course_id": "C080", "title": "Svelte & SvelteKit: The Complete Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Web Development", "level": "Intermediate", "rating": 4.8, "duration_hours": 14, "price_usd": 19.99, "skills_covered": "Svelte; SvelteKit; Reactive Declarations; Stores; SSR; Routing", "prerequisites": "HTML CSS JS", "description": "Build ultra-fast lightweight frontend web applications with zero virtual DOM overhead using Svelte.", "url": "https://www.udemy.com/course/sveltejs-the-complete-guide/"},
    {"course_id": "C081", "title": "Vue - The Complete Guide (incl. Router and Pinia)", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Web Development", "level": "Intermediate", "rating": 4.7, "duration_hours": 32, "price_usd": 19.99, "skills_covered": "Vue 3; Composition API; Vue Router; Pinia; Vite; Single Page Apps", "prerequisites": "HTML CSS JS", "description": "Master Vue.js 3 from ground up including the Composition API state management and SSR.", "url": "https://www.udemy.com/course/vuejs-2-the-complete-guide/"},
    {"course_id": "C082", "title": "C# 12 and .NET 8 - Modern Cross-Platform Development", "provider": "Packt / Udemy", "category": "Software Engineering", "level": "Intermediate", "rating": 4.6, "duration_hours": 30, "price_usd": 19.99, "skills_covered": "C#; .NET 8; Entity Framework; LINQ; Web APIs; Blazor", "prerequisites": "Basic Programming", "description": "Build scalable modern cross-platform web and cloud applications using C# and .NET 8.", "url": "https://www.udemy.com/course/c-sharp-dotnet/"},
    {"course_id": "C083", "title": "Rust for Backend Web Development", "provider": "Zero To Mastery", "category": "Software Engineering", "level": "Advanced", "rating": 4.8, "duration_hours": 20, "price_usd": 39.00, "skills_covered": "Rust; Axum; Tokio; SQLx; Async Rust; Docker; Production Deployments", "prerequisites": "Rust Basics", "description": "Build robust blazing-fast memory-safe backend REST APIs and microservices using Axum and Tokio.", "url": "https://zerotomastery.io/courses/learn-rust/"},
    {"course_id": "C084", "title": "Database Management Systems (DBMS)", "provider": "NPTEL (IIT Kharagpur)", "category": "Computer Science", "level": "Beginner", "rating": 4.7, "duration_hours": 40, "price_usd": 0.00, "skills_covered": "ER Modeling; Relational Algebra; SQL; Normalization; Indexing; B+ Trees; ACID", "prerequisites": "None", "description": "Comprehensive university curriculum covering relational database theory normalization and transaction management.", "url": "https://nptel.ac.in/courses/106105175"},
    {"course_id": "C085", "title": "Compilers: Principles Techniques and Tools", "provider": "Stanford Online", "category": "Computer Science", "level": "Advanced", "rating": 4.8, "duration_hours": 60, "price_usd": 0.00, "skills_covered": "Lexical Analysis; Parsing; AST; Type Checking; Intermediate Code; Optimization", "prerequisites": "C or C++", "description": "Understand how high-level programming languages are parsed analyzed and compiled to machine code.", "url": "https://online.stanford.edu/courses/soe-ycs0002-compilers"},
    {"course_id": "C086", "title": "Cloud Native Microservices with Kubernetes and Istio", "provider": "Udemy (Richard Chesterwood)", "category": "Cloud & DevOps", "level": "Advanced", "rating": 4.7, "duration_hours": 18, "price_usd": 19.99, "skills_covered": "Service Mesh; Istio; Envoy; Traffic Management; Mutual TLS; Telemetry", "prerequisites": "Kubernetes Basics", "description": "Implement secure observable and reliable service mesh architectures using Istio on Kubernetes.", "url": "https://www.udemy.com/course/istio-hands-on/"},
    {"course_id": "C087", "title": "Ansible for the Absolute Beginner", "provider": "Udemy (Mumshad Mannambeth)", "category": "Cloud & DevOps", "level": "Beginner", "rating": 4.7, "duration_hours": 8, "price_usd": 19.99, "skills_covered": "Ansible; Playbooks; YAML; Inventory; Modules; Server Configuration", "prerequisites": "Linux Basics", "description": "Automate server configuration package installation and infrastructure deployments with Ansible.", "url": "https://www.udemy.com/course/ansible-for-the-absolute-beginner/"},
    {"course_id": "C088", "title": "GitHub Actions - The Complete Guide", "provider": "Udemy (Maximilian Schwarzmüller)", "category": "Cloud & DevOps", "level": "Intermediate", "rating": 4.8, "duration_hours": 8, "price_usd": 19.99, "skills_covered": "GitHub Actions; CI/CD; Workflows; Automated Testing; Deployment; Secrets", "prerequisites": "Git Basics", "description": "Build production CI/CD automation pipelines directly inside your GitHub repositories.", "url": "https://www.udemy.com/course/github-actions-the-complete-guide/"},
    {"course_id": "C089", "title": "Practical Malware Analysis & Triage", "provider": "TCM Security", "category": "Cybersecurity", "level": "Advanced", "rating": 4.9, "duration_hours": 15, "price_usd": 29.99, "skills_covered": "Static Analysis; Dynamic Analysis; Ghidra; x64dbg; Sandboxing; YARA", "prerequisites": "C Basics; Assembly", "description": "Learn practical techniques to dissect malware samples safely extract IOCs and understand payloads.", "url": "https://academy.tcm-sec.com/p/practical-malware-analysis-triage"},
    {"course_id": "C090", "title": "Network Defense and Countermeasures", "provider": "Coursera (EC-Council)", "category": "Cybersecurity", "level": "Intermediate", "rating": 4.6, "duration_hours": 28, "price_usd": 49.00, "skills_covered": "Firewalls; IDS/IPS; VPNs; Network Hardening; Defense-in-Depth", "prerequisites": "Networking Basics", "description": "Implement defensive security postures to protect corporate network infrastructure from perimeter threats.", "url": "https://www.coursera.org/learn/network-defense-countermeasures"},
    {"course_id": "C091", "title": "Practical Deep Learning for Computer Vision", "provider": "Coursera (DeepLearning.AI)", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.7, "duration_hours": 30, "price_usd": 49.00, "skills_covered": "YOLOv8; Torchvision; ResNet; Data Augmentation; Object Detection", "prerequisites": "Python; PyTorch", "description": "Build industrial computer vision applications for edge devices and cloud inference servers.", "url": "https://www.coursera.org/specializations/deep-learning"},
    {"course_id": "C092", "title": "Vector Search and Embeddings Masterclass", "provider": "Pinecone Academy", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.8, "duration_hours": 10, "price_usd": 0.00, "skills_covered": "Embeddings; Vector Databases; HNSW; Cosine Similarity; Hybrid Search; RAG", "prerequisites": "Python Basics", "description": "Master high-dimensional vector search similarity metrics and index tuning for enterprise AI search.", "url": "https://www.pinecone.io/learn/"},
    {"course_id": "C093", "title": "Building Agents with AutoGen", "provider": "DeepLearning.AI & Microsoft", "category": "AI & Machine Learning", "level": "Advanced", "rating": 4.8, "duration_hours": 6, "price_usd": 0.00, "skills_covered": "AutoGen; Conversational Agents; Code Execution; Multi-Agent Groups", "prerequisites": "Python", "description": "Create multi-agent conversational systems with autonomous tool execution using Microsoft AutoGen.", "url": "https://www.deeplearning.ai/short-courses/building-agentic-rag-with-llamaindex/"},
    {"course_id": "C094", "title": "Agentic Design Patterns", "provider": "DeepLearning.AI", "category": "AI & Machine Learning", "level": "Intermediate", "rating": 4.9, "duration_hours": 5, "price_usd": 0.00, "skills_covered": "Reflection; Tool Use; Planning; Multi-Agent Collaboration; Agentic Workflows", "prerequisites": "Python", "description": "Explore key architectural patterns for building resilient autonomous AI agents with LLMs.", "url": "https://www.deeplearning.ai/short-courses/"},
    {"course_id": "C095", "title": "Introduction to UI Design", "provider": "Coursera (University of Minnesota)", "category": "UI/UX Design", "level": "Beginner", "rating": 4.6, "duration_hours": 15, "price_usd": 49.00, "skills_covered": "Visual Hierarchy; Typography; Color Theory; Grid Systems; Interface Layout", "prerequisites": "None", "description": "Learn visual design fundamentals to create clean readable and engaging digital user interfaces.", "url": "https://www.coursera.org/learn/ui-design"},
    {"course_id": "C096", "title": "Accessibility for Web Developers", "provider": "Google Developers / web.dev", "category": "Web Development", "level": "Beginner", "rating": 4.9, "duration_hours": 12, "price_usd": 0.00, "skills_covered": "WCAG; ARIA; Screen Readers; Color Contrast; Keyboard Navigation", "prerequisites": "HTML CSS JS", "description": "Learn how to build inclusive accessible digital experiences adhering to modern WCAG guidelines.", "url": "https://web.dev/learn/accessibility/"},
    {"course_id": "C097", "title": "AI Product Management Specialization", "provider": "Coursera (Duke University)", "category": "UI/UX Design", "level": "Beginner", "rating": 4.7, "duration_hours": 20, "price_usd": 49.00, "skills_covered": "Machine Learning for PMs; AI Ethics; Project Scoping; KPI Definition", "prerequisites": "None", "description": "Learn how to manage and deliver machine learning products from user need identification to deployment.", "url": "https://www.coursera.org/specializations/ai-product-management-duke"},
    {"course_id": "C098", "title": "Unreal Engine 5 C++ The Ultimate Game Developer Course", "provider": "Udemy (Stephen Ulibarri)", "category": "Software Engineering", "level": "Intermediate", "rating": 4.8, "duration_hours": 45, "price_usd": 19.99, "skills_covered": "Unreal Engine 5; C++; Gameplay Framework; AI Behavior Trees; Materials", "prerequisites": "C++ Basics", "description": "Learn C++ game programming from scratch by building an action-adventure RPG in Unreal Engine 5.", "url": "https://www.udemy.com/course/unreal-engine-5-the-ultimate-game-developer-course/"},
    {"course_id": "C099", "title": "Modern Computer Architecture and Organization", "provider": "Carnegie Mellon University", "category": "Computer Science", "level": "Advanced", "rating": 4.9, "duration_hours": 75, "price_usd": 0.00, "skills_covered": "Pipelining; Cache Coherence; Out-of-Order Execution; Branch Prediction; VLIW", "prerequisites": "C and Digital Logic", "description": "CMU legendary course on processor design memory hierarchy and hardware performance acceleration.", "url": "https://www.cs.cmu.edu/~213/"},
    {"course_id": "C100", "title": "Apache Spark 3 - Real-Time Data Engineering", "provider": "Udemy (Frank Kane)", "category": "Data Science", "level": "Intermediate", "rating": 4.7, "duration_hours": 16, "price_usd": 19.99, "skills_covered": "Apache Spark; PySpark; Spark Streaming; DataFrames; Big Data; Cluster Computing", "prerequisites": "Python Basics", "description": "Process massive datasets in real-time with distributed computing using Apache Spark 3 and Python.", "url": "https://www.udemy.com/course/taming-big-data-with-apache-spark-hands-on/"}
]

fieldnames = [
    "course_id", "title", "provider", "category", "level",
    "rating", "duration_hours", "price_usd", "skills_covered",
    "prerequisites", "description", "url"
]

out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "courses.csv")
os.makedirs(os.path.dirname(out_path), exist_ok=True)

with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
    writer.writeheader()
    for row in courses:
        writer.writerow(row)

print(f"Generated clean courses.csv with {len(courses)} courses at {out_path}")
